# Generated by Django 6.0.7 on 2026-07-17 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcomment',
            options={'ordering': ['created_at']},
        ),
    ]
